---
name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  id-token: write # to authenticate with OIDC when publishing to npm
  pages: write # to deploy to Pages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: pnpm publish --no-git-checks
      - run: pnpm run docs
      - name: "Upload docs as pages artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
      - name: "Deploy the uploaded pages artifact"
        uses: actions/deploy-pages@v4
